// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXOi6bEtrdD1CuuI74sAdCru99yqJcds',
    appId: '1:406377590170:web:fd7b2ea379e09bc842de23',
    messagingSenderId: '406377590170',
    projectId: 'gaweeapp-945db',
    authDomain: 'gaweeapp-945db.firebaseapp.com',
    storageBucket: 'gaweeapp-945db.firebasestorage.app',
    measurementId: 'G-28B1JMGTD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6wTErk9wxSxo5lSciLXVYNkgroPWHTs',
    appId: '1:406377590170:android:3fec7c920e8c43d142de23',
    messagingSenderId: '406377590170',
    projectId: 'gaweeapp-945db',
    storageBucket: 'gaweeapp-945db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCck-gpXLhLMiQN9EsHGHxwX0k0EEJf5XA',
    appId: '1:406377590170:ios:7d1f0eb11a7cbcad42de23',
    messagingSenderId: '406377590170',
    projectId: 'gaweeapp-945db',
    storageBucket: 'gaweeapp-945db.firebasestorage.app',
    iosBundleId: 'com.gaweapp.mobilewebser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCck-gpXLhLMiQN9EsHGHxwX0k0EEJf5XA',
    appId: '1:406377590170:ios:c41b75e8f20d15a442de23',
    messagingSenderId: '406377590170',
    projectId: 'gaweeapp-945db',
    storageBucket: 'gaweeapp-945db.firebasestorage.app',
    iosBundleId: 'com.example.coba1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUXOi6bEtrdD1CuuI74sAdCru99yqJcds',
    appId: '1:406377590170:web:12105fccb158f35c42de23',
    messagingSenderId: '406377590170',
    projectId: 'gaweeapp-945db',
    authDomain: 'gaweeapp-945db.firebaseapp.com',
    storageBucket: 'gaweeapp-945db.firebasestorage.app',
    measurementId: 'G-6RPC6ZVS34',
  );
}
